### ISSUE TITLE
Update website design to match MSAM.media style

### ISSUE THREAD

**Issue by MSAMmedia** [MSAMmedia/MSAM-media-test#4]
## Website Design Update

The current implementation needs to be updated to match the MSAM.media design aesthetic. Here are the required changes:

### Header Section
- Update the navigation to use the translucent dark overlay style
- Add the MSAM.media logo with proper styling
- Implement the full-width hero banner with overlay gradient
- Move navigation items to match the exact spacing and style

### Main Content
- Remove the current sections layout
- Implement the portfolio grid layout similar to the main site
- Add proper image containers with hover effects
- Match the dark theme and gradient overlays

### Typography
- Use the correct font family throughout
- Implement proper spacing between elements
- Match the exact font weights and sizes

### Color Scheme
- Update to match the MSAM.media color palette
- Implement proper gradients and overlays
- Match the exact transparency levels

### Specific Changes Needed
1. Replace current navigation with translucent version
2. Implement full-width hero section with proper gradient overlay
3. Add portfolio grid layout
4. Update typography to match brand guidelines
5. Implement proper color scheme and gradients
6. Add hover effects and transitions
7. Update spacing and alignment

### References
The design should exactly match:
- Navigation style from msam.media
- Hero section with centered content
- Portfolio grid layout
- Dark theme with proper overlays

Would you like me to create a separate branch for these changes and start implementing them?

**Comment by MSAMmedia** [comment]
## Technical Implementation Details

### Navigation
```css
/* Nav styles */
.nav-container {
  background: rgba(0, 0, 0, 0.3);
  backdrop-filter: blur(8px);
}
```

### Typography
- Font Family: System font stack with fallbacks
- Font Weights: 
  - Light: 300
  - Regular: 400
- Letter Spacing: 
  - Normal: 0.025em
  - Wide: 0.05em

### Color Palette
```css
:root {
  --background: #000000;
  --overlay-dark: rgba(0, 0, 0, 0.8);
  --overlay-light: rgba(0, 0, 0, 0.3);
  --text-primary: #ffffff;
  --text-secondary: rgba(255, 255, 255, 0.7);
}
```

### Grid Layout
- Desktop: 4 columns
- Tablet: 2 columns
- Mobile: 1 column
- Gap: 1rem (16px)
- Aspect ratio: 4:3

### Hover Effects
- Images: Scale 1.1 with smooth transition
- Text: Opacity transition
- Buttons: Background opacity change

### Components Structure
```jsx
<Layout>
  <Nav />
  <Hero />
  <PortfolioGrid>
    <PortfolioItem /> // Repeated
  </PortfolioGrid>
  <Footer />
</Layout>
```

### Responsive Breakpoints
- Mobile: < 768px
- Tablet: 768px - 1024px
- Desktop: > 1024px

All components are built using React and styled with Tailwind CSS. The layout is fully responsive and maintains the proper aspect ratios and spacing across all screen sizes.
